# --------------------------- #
#
# Tutorial:
# Seascape Redundancy Analysis
# 
# Description:
# Prepare spatial data for redundancy analysis.
#
# Data:
# European lobster SNP genotypes generated by a Fluidigm EP1 system.
# Tutorial uses 37 sites from the original study (Jenkins et al. 2019).
# https://doi.org/10.1111/eva.12849.
#
# Notes before execution:
# 1. Make sure all required R packages are installed.
# 2. Set working directory to the location of this R script.
#
# --------------------------- #

# Load packages
library(dplyr)
library(raster)
library(marmap)
library(ade4)
library(adespatial)
library(SoDA)
library(psych)

# Import coordinates of sites
coords = read.csv("coordinates.csv")
names(coords)


#--------------#
#
# Compute dbMEMs
#
#--------------#

# Further info on distance-based Moran's Eigenvector Maps in the vignette
# vignette("tutorial", package = "adespatial")

# Transform geographic coordinates into cartesian coordinates
cart = geoXY(coords$Lat, coords$Lon)

# Calculate euclidian distances
euclidian_distances = dist(cart, method = "euclidean") 

# Compute distance-based Moran's Eigenvector Maps
dbmems = dbmem(euclidian_distances, thresh = NULL)
dbmems

# Plot dbMEM eigenvalues
pairs.panels(dbmems, scale = FALSE)

# Export dbMEMs
write.csv(dbmems, file = "dbmems.csv", row.names = FALSE)
